pipeline {
    agent any

    stages {
        stage('Compile') {
            steps {
                bat 'mvn compile'
            }
        }

        stage('Unit Test') {
            steps {
                bat 'mvn test'
            }
        }

        stage('Static Code Analysis') {
            steps {
                // Run Checkstyle validation
                bat 'mvn checkstyle:check'

                // Generate HTML report
                bat 'mvn checkstyle:checkstyle'

                // Publish Checkstyle report to Jenkins UI
                publishHTML(target: [
                    reportDir: 'target/site',       // Maven default Checkstyle HTML location
                    reportFiles: 'checkstyle.html', // HTML report generated by Maven
                    reportName: "Checkstyle Report"
                ])
            }
        }

        stage('Code Coverage') {
            steps {
                // Generate JaCoCo coverage report
                bat 'mvn jacoco:report'

                // Optionally enforce coverage threshold
                // bat 'mvn jacoco:check'

                // Publish JaCoCo report to Jenkins UI
                publishHTML(target: [
                    reportDir: 'target/site/jacoco',
                    reportFiles: 'index.html',
                    reportName: 'JaCoCo Coverage Report'
                ])
            }
        }
    }
}
